### This is basically our service configuration file. 


service: elevator-rest-api
frameworkVersion: '2'

provider:
  name: aws
  region: eu-west-1 ##This can be changed to suit the location you are, eu-west-1 is Ireland
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

functions:
  app:
    handler: handler.app
    events: ##http trigger
      - http: any {proxy+}  ##any method is ok here (GET,PUT,POST), proxy+ tells API Gateway that no matter which endpoint you get, to proxy off this request. 

resources:
  Resources:
    usersTable: ##Specifying DynamoDB usersTable
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    buildingsTable: ##Specifying DynamoDB buildingsTable
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: buildingsTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    elevatorsTable: ##Specifying DynamoDB elevatorsTable
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: elevatorsTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


