
service: elevator-rest-api
frameworkVersion: '2'

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

functions:
  app:
    handler: handler.app
    events:
      - http: any {proxy+} 

